---
driver:
  name: docker
  privileged: true

driver_config:
  socket: <%= ENV['DOCKER_HOST'] %>
  privileged: true
  provision_command:
    - echo "SSHD_OPTS='-o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid'" > /etc/default/ssh
  run_command: /sbin/init
  cap_add:
    - ALL
    - SYS_ADMIN
    - NET_ADMIN
    - NET_BIND_SERVICE
    - NET_BROADCAST

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_pip: true
  ansible_verbose: true
  ansible_version: 2.2.1.0
  require_chef_for_busser: false

platforms:
  - name: debian-jessie
    driver:
      image: debian:8
  - name: ubuntu-14.04
    driver:
      image: ubuntu-upstart:14.04
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04

verifier:
  name: inspec
  attributes:
    using_docker: true

suites:
  - name: default
