---
sudo: required
# docker is required to run tests
services: docker

install:
  - pip install ansible
  - bundle install
  - "echo '[defaults].' > ansible.cfg"
  - "echo 'roles_path = ../' >> ansible.cfg"

branches:
  only:
    - develop
    - master

env:
  matrix:
  - INSTANCE=default-ubuntu-1604
  #- INSTANCE=default-ubuntu-1404
  #- INSTANCE=default-debian-jessie

before_script:
  - ansible-playbook -i test/integration/default/inventory test/integration/default/default.yml --syntax-check

script:
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml kitchen test ${INSTANCE}
