- name: Install mailcatcher dependencies
  apt:
    state: present
    name:
      - build-essential
      - sqlite3
      - libsqlite3-dev
      - ruby-dev
      - ruby

- name: Logfile permissions
  file:
		path: /var/log/mailcatcher.log
    owner: mailcatcher
    group: mailcatcher
    state: touch


- name: Check for mailcatcher
  stat:
    path=/usr/local/bin/mailcatcher
  register: mailcatcher_installed

- name: Install Mailcatcher
  command: gem install mailcatcher
  when: not mailcatcher_installed.stat.exists

- name: Create upstart script for mailcatcher
  template: src=mailcatcher.j2 dest=/etc/init/mailcatcher.conf mode=0644
  notify:
    - restart mailcatcher
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version | int <= 7) or
			  (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int <= 14)

- name: Create systemd script for mailcatcher
  template: src=mailcatcher.service.j2 dest=/etc/systemd/system/mailcatcher.service mode=0644
  notify:
    - restart mailcatcher
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version | int > 7) or
			  (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int > 14)
